### PR TITLE
Add Traefik Labs Blog Post

### PR DESCRIPTION
**Pull request by SantoDE**
Hey there 👋

We just released a blog post and a plugin, on how Traefik can help mitigate the issue. I think would be nice to have it in the list

### CODE REVIEW

**Review by mattj-io — CHANGES_REQUESTED** [review]
Thanks for the contribution ! Since the plugin is already linked in the article, could we just include the article ? One other small nit, could you end the line in a period - otherwise it fails the linting tests.

**Comment by mattj-io** [comment]
One more check, is this functionality available to free users ? We're trying to keep the list free/OSS as much as possible.

**Comment by SantoDE** [comment]
List updated @mattj-io 

Yes, its available to all users (of course including free). You can either download the plugin code and just run it locally, or you register for a free account and download the plugin from our registry.

**Comment by mattj-io** [comment]
Perfect. Merged ! Thanks again for your contribution

**Pull request merged**
